/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function convertTTFToWOFF2(input: Buffer): Buffer
export function convertTTFToWOFF2Async(input: Buffer, signal?: AbortSignal | undefined | null): Promise<Buffer>
