/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function convertTTFToWOFF2(input: Uint8Array, params?: Woff2Params | undefined | null): Uint8Array

export declare function convertTTFToWOFF2Async(input: Uint8Array, params?: Woff2Params | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>

export declare function convertWOFF2ToTTF(input: Uint8Array): Buffer

export declare function convertWOFF2ToTTFAsync(input: Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>

export interface Woff2Params {
  extendedMetadata?: string
  brotliQuality?: number
  allowTransforms?: boolean
}
